var bazaSkladnikow = [

////////////          NAPOJE          ////////////
'ajerkoniak',
'brandy',
'coca-cola',
'coca-cola light',
'likier',
'gin',
'herbata bez cukru',
'jałowcówka',
'kakao',
'kawa bez cukru',
'kawa cappuccino',
'kawa rozpuszczalna',
'kawa zbożowa bez cukru',
'kawa zbożowa',
'koniak',
'likier kminkowy',
'likier orzechowy',
'likier ziołowy',
'napój Fanta',
'napój jabłkowy',
'napój Red Bull',
'napój Sprite',
'napój z czarnej porzeczki',
'nektar jabłkowy antonówka',
'pepsi cola',
'pepsi cola light',
'piwo bezalkoholowe',
'piwo ciemne',
'piwo ciemne pełne',
'piwo imbirowe',
'piwo jasne',
'piwo jasne pełne',
'piwo korzenne',
'porter',
'porto',
'portwein',
'rum',
'sok ananasowy',
'sok cytrynowy',
'sok grejpfrutowy',
'sok gruszkowy',
'sok jabłkowy',
'sok marchwiowy',
'sok pomarańczowy',
'sok pomidorowy',
'sok z buraków',
'sok z pomidorów',
'sok z winogron',
'szampan',
'szampan półsłodki',
'szampan półwytrawny',
'szampan słodki',
'tonik',
'whisky',
'wino białe musujące',
'wino białe półwytrawne',
'wino białe słodkie',
'wino białe wytrawne',
'wino czerwone',
'wino czerwone półsłodkie',
'wino czerwone słodkie',
'wino czerwone wytrawne',
'woda mineralna',
'wódka',

////////////          OWOCE          ////////////
'agrest',
'ananas',
'arbuz',
'awokado',
'banan',
'banan suszony',
'borówki',
'brzoskwinia',
'brzoskwinia, mus',
'brzoskwinia suzona',
'brzoskwinia w syropie',
'cytryna',
'czarne jagody',
'czereśnie',
'czereśnie suszone',
'daktyle',
'daktyle suszone',
'dynia',
'dżem wiśniowy',
'figi suszone',
'figi świeże',
'granat',
'grejpfrut',
'grejpfrut czerwony',
'gruszka',
'gruszka suszona',
'jabłko',
'jabłka suszone',
'jeżyny',
'kiwi',
'limonka',
'maliny',
'mandarynka',
'mango',
'marakuja',
'marmolada',
'melon',
'morele',
'morele suszone',
'nektarynka',
'papaja',
'pigwa',
'pomarańcze',
'porzeczki czarne',
'porzeczki czerwone',
'poziomki',
'śliwki',
'truskawki',
'winogrona',
'wiśnie',
'wiśnie suszone',
'żurawina',
];
var dayArr = Array( 
	{ "tytul" : "Russian apple", "skladniki" : ["wódka", "sok żurawinowy", "sok ananasowy", "kostki lodu"], "przepis" : "Do shakera wrzucamy kilka kostek lodu. Wlewamy wszystkie trzy składniki i dokładnie wstrząsamy. Następnie rozlewamy wszystko do kieliszków." }, 
	);
var myObjects = [
        {
            tytul: "Russian apple",
            skladniki: ["wódka", "sok żurawinowy", "sok ananasowy", "kostki lodu"],
            przepis: "Do shakera wrzucamy kilka kostek lodu. Wlewamy wszystkie trzy składniki i dokładnie wstrząsamy. Następnie rozlewamy wszystko do kieliszków."
        },
        {
            tytul: "Blue shark",
            skladniki: ["wódka", "tequila ", "likier blue curacao", "kruszony lód"],
            przepis: "Do shakera wrzuć kruszony lód. Wlej wszystkie składniki i dokładnie wstrząśnij. Zawartość shakera (wraz z lodem) przelej do szklanki typu old-fashioned."
        }
    ];

		